"""
Django settings for erp project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@$v^t6^aont_-2t^vqk_g5go-45^e=r-fwx78q^ldjak+_$c_2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["62.72.57.19","*"]

CORS_ALLOWED_ORIGINS = ["*"]
BASE_URL = 'http://54.90.126.75' #'http://100.26.54.21'#
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'login',
    'supplier',
    'customer',
    'sales',
    'commonApp',
    'accounting',
    'production',
    
]
# ASGI_APPLICATION = 'erp.asgi.application'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'erp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'erp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'mysql.connector.django',
#         'NAME': 'erp',   # Replace with your MySQL database name
#         'USER': 'root',   # Replace with your MySQL database user
#         'PASSWORD': 'Rusingle@7866',  # Replace with your MySQL database password
#         'HOST': 'localhost',            # Replace with your MySQL host (e.g., 'localhost' or '127.0.0.1')
#         'PORT': '3306',                 # Replace with your MySQL port if it's not the default (3306)
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS=[
        os.path.join(BASE_DIR,'static'),
        ]


# Add the CDN URL to be excluded
EXCLUDED_CDN_URLS = ['https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css']

# Update the STATICFILES_DIRS setting
STATICFILES_DIRS = [
    # Other static file paths...
    os.path.join(BASE_DIR, 'static'),
]

# Exclude CDN URLs from finders
STATICFILES_EXCLUDED_URLS = [os.path.join(url, '*') for url in EXCLUDED_CDN_URLS]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


DATETIME_FORMAT = '%Y-%m-%d %H:%m:%s'


AUTH_USER_MODEL = 'login.CustomUser'



TELEGRAM_BOT_TOKEN = '6892855782:AAGTkmOKGRBCqNfSfVw4I1HGHNY1ttToTU4'
ERP = 'Red Rock ERP'

