# Generated by Django 4.2.4 on 2023-12-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_customuser_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='name',
            field=models.CharField(choices=[('Supplier', 'Supplier'), ('HR_MANAGER', 'HR Manager'), ('ACCOUNTANT', 'Accountant'), ('Agent', 'Agent'), ('Customer', 'Customer')], max_length=50, unique=True),
        ),
    ]
