# Generated by Django 4.2.4 on 2023-12-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_accounttype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('SALES', 'Sales'), ('ACCOUNT', 'Accounting'), ('INVENTORY', 'Inventory'), ('ADMIN', 'Administration'), ('NONE', 'None')], max_length=100, verbose_name='Department Name'),
        ),
    ]
