# Generated by Django 4.2.4 on 2024-01-14 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_rename_phone_number_customuser_gst_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='ledger',
            new_name='ledgers',
        ),
    ]
