# Generated by Django 4.2.4 on 2024-01-14 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_rename_ledger_customuser_ledgers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='ledgers',
            new_name='ledger',
        ),
    ]
