# Generated by Django 4.2.4 on 2024-01-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_rename_ledgers_customuser_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='credit_period',
            field=models.IntegerField(default=7),
        ),
    ]
