# Generated by Django 4.2.4 on 2024-01-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_customuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='name',
            field=models.CharField(choices=[('Supplier', 'Supplier'), ('Accountant', 'Accountant'), ('Agent', 'Agent'), ('Customer', 'Customer')], max_length=50, unique=True),
        ),
    ]
