# Generated by Django 4.2.4 on 2024-01-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_remove_billing_company_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
