# Generated by Django 4.2.4 on 2024-01-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0021_productstock_delivery'),
        ('production', '0002_remove_production_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrow',
            name='package',
            field=models.ManyToManyField(to='commonApp.product'),
        ),
        migrations.AddField(
            model_name='productionrow',
            name='packageQuantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionrow',
            name='quantityPerPackage',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
