# Generated by Django 4.2.4 on 2024-01-01 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0021_productstock_delivery'),
        ('production', '0003_productionrow_package_productionrow_packagequantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionrow',
            name='package',
        ),
        migrations.AddField(
            model_name='productionrow',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commonApp.product'),
            preserve_default=False,
        ),
    ]
