# Generated by Django 4.2.4 on 2024-01-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_remove_productionrow_package_productionrow_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrow',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
