# Generated by Django 4.2.4 on 2024-01-01 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0021_productstock_delivery'),
        ('production', '0005_alter_productionrow_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrow',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_product', to='commonApp.product'),
        ),
    ]
