# Generated by Django 4.2.4 on 2024-01-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_productionrow_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionrow',
            old_name='quantity',
            new_name='TotalQuantity',
        ),
        migrations.RemoveField(
            model_name='productionrow',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productionrow',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='productionrow',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='productionrow',
            name='row_type',
            field=models.CharField(choices=[('Raw', 'Raw'), ('Package', 'Package')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
