# Generated by Django 4.2.4 on 2024-01-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_rename_quantity_productionrow_totalquantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrow',
            name='packageQuantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionrow',
            name='quantityPerPackage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
