# Generated by Django 4.2.4 on 2024-01-01 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0021_productstock_delivery'),
        ('production', '0008_alter_productionrow_packagequantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrow',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commonApp.product'),
        ),
    ]
