# Generated by Django 4.2.4 on 2024-01-01 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_alter_productionrow_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrow',
            name='production_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Production',
        ),
    ]
