# Generated by Django 4.2.4 on 2024-01-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_productionrow_production_date_delete_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrow',
            name='TotalCost',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
