# Generated by Django 4.2.4 on 2024-01-02 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0022_alter_productstock_type'),
        ('accounting', '0035_salesquotation_status'),
        ('production', '0012_alter_productionrow_totalcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducedRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_type', models.CharField(choices=[('Raw', 'Raw'), ('Package', 'Package')], max_length=20)),
                ('packageQuantity', models.PositiveIntegerField(default=0)),
                ('quantityPerPackage', models.PositiveIntegerField(default=0)),
                ('TotalQuantity', models.PositiveIntegerField()),
                ('TotalCost', models.DecimalField(decimal_places=2, max_digits=50)),
                ('production_date', models.DateField(auto_now_add=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commonApp.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_product', to='commonApp.product')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.salesquotation')),
            ],
        ),
    ]
