# Generated by Django 4.2.4 on 2024-01-13 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_alter_producedrow_production_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='producedrow',
            name='production_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producedrow',
            name='production_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
