# Generated by Django 4.2.4 on 2024-01-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0002_remove_employee_name_employee_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='hours_worked',
        ),
        migrations.AddField(
            model_name='attendance',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='attendance_csv/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
