# Generated by Django 4.2.4 on 2024-01-09 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0003_remove_attendance_hours_worked_attendance_csv_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='joining',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='working_days',
            field=models.IntegerField(default=30),
        ),
    ]
