# Generated by Django 4.2.4 on 2024-01-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0004_employee_joining_employee_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employe_id',
            field=models.CharField(default='emp-1', max_length=50),
            preserve_default=False,
        ),
    ]
