# Generated by Django 4.2.4 on 2024-01-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0005_employee_employe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employe_id',
            new_name='employee_id',
        ),
    ]
