# Generated by Django 4.2.4 on 2024-01-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0007_remove_attendance_csv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('paid-leave', 'Paid-Leave'), ('unpaid-leave', 'Unpaid-Leave')], max_length=50),
        ),
    ]
