# Generated by Django 4.2.4 on 2023-12-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherLedgerVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('CV', 'Contra Voucher'), ('SV', 'Sales Voucher'), ('PV', 'Purchase Voucher'), ('JV', 'Journal Voucher'), ('CNV', 'Credit Note Voucher'), ('DNV', 'Debit Note Voucher'), ('SJV', 'Stock Journal Voucher'), ('PAV', 'Payment Advice Voucher'), ('RAV', 'Receipt Advice Voucher')], max_length=3)),
                ('selected_groups', models.ManyToManyField(to='accounting.group')),
            ],
            options={
                'verbose_name_plural': 'Voucher Ledger Visibility',
            },
        ),
    ]
