# Generated by Django 4.2.4 on 2023-12-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_purchasequotation_quotation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasequotation',
            name='expiry_date',
        ),
    ]
