# Generated by Django 4.2.4 on 2023-12-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_remove_purchasequotation_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasequotation',
            old_name='tax_total',
            new_name='csgst_total',
        ),
        migrations.AddField(
            model_name='purchasequotation',
            name='sgst_total',
            field=models.CharField(default=100, max_length=255),
            preserve_default=False,
        ),
    ]
