# Generated by Django 4.2.4 on 2023-12-13 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_rename_tax_total_purchasequotation_csgst_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('quotation_number', models.AutoField(primary_key=True, serialize=False)),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField(blank=True)),
                ('quotation_date', models.DateField(auto_now_add=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('notes_comments', models.TextField(blank=True, null=True)),
                ('sub_total', models.CharField(max_length=255)),
                ('csgst_total', models.CharField(max_length=255)),
                ('sgst_total', models.CharField(max_length=255)),
                ('final_amt', models.CharField(max_length=255)),
                ('Others', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItemRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('PurchaseQuotation', 'PurchaseQuotation')], max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.CharField(max_length=255)),
                ('total_price', models.CharField(max_length=255)),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.purchaseinvoice')),
            ],
        ),
    ]
