# Generated by Django 4.2.4 on 2023-12-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_purchaseinvoice_purchaseinvoiceitemrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasequotation',
            name='quotation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
