# Generated by Django 4.2.4 on 2023-12-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_remove_purchasequotation_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasequotation',
            name='status',
        ),
        migrations.AddField(
            model_name='purchaseitemrow',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
