# Generated by Django 4.2.4 on 2023-12-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_alter_purchaseitemrow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitemrow',
            name='status',
            field=models.BooleanField(choices=[('ACTIVE', True), ('INACTIVE', False)], max_length=20),
        ),
    ]
