# Generated by Django 4.2.4 on 2023-12-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_alter_purchaseitemrow_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitemrow',
            name='status',
        ),
        migrations.AddField(
            model_name='purchasequotation',
            name='status',
            field=models.BooleanField(choices=[('ACTIVE', True), ('INACTIVE', False)], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
