# Generated by Django 4.2.4 on 2023-12-16 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_remove_purchaseitemrow_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_type', models.CharField(choices=[('AGENT', 'AGENT'), ('SUPPLIER', 'SUPPLIER')], max_length=20)),
                ('supplierBid', models.CharField(max_length=255)),
                ('agentcommision', models.CharField(default=0, max_length=255)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('prductRow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='accounting.purchaseitemrow')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quotationitems', to='accounting.purchasequotation')),
            ],
        ),
    ]
