# Generated by Django 4.2.4 on 2023-12-18 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commonApp', '0018_alter_deliverydetails_status'),
        ('accounting', '0017_bids'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesQuotation',
            fields=[
                ('quotation_number', models.AutoField(primary_key=True, serialize=False)),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField(blank=True)),
                ('quotation_date', models.DateField(auto_now_add=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('notes_comments', models.TextField(blank=True, null=True)),
                ('sub_total', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(choices=[(True, 'ACTIVE'), (False, 'INACTIVE')], max_length=20)),
                ('approval', models.BooleanField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Pending', 'Pending')], max_length=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesItemRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent')], max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.CharField(max_length=255)),
                ('total_price', models.CharField(max_length=255)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='commonApp.product')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.salesquotation')),
            ],
        ),
    ]
