# Generated by Django 4.2.4 on 2023-12-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_remove_salesquotation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesquotation',
            name='approval',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Pending', 'Pending'), ('DeliverPending', 'DeliverPending'), ('Completed', 'Completed')], max_length=20),
        ),
    ]
