# Generated by Django 4.2.4 on 2023-12-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_alter_salesquotation_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesquotation',
            name='commision',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
