# Generated by Django 4.2.4 on 2023-12-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_alter_salesdeliverydetails_final_quantity_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdeliverydetails',
            name='final_quantity_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
