# Generated by Django 4.2.4 on 2023-12-19 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_salesdeliverydetails_orderfk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdeliverydetails',
            name='final_quantity_price',
        ),
    ]
