# Generated by Django 4.2.4 on 2023-12-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_salesdeliverydetails_final_quantity_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdeliverydetails',
            name='final_quantity_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
