# Generated by Django 4.2.4 on 2024-01-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_purchasequotation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesquotation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('inProduction', 'In Production'), ('Produced', 'Produced')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
