# Generated by Django 4.2.4 on 2024-01-08 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0027_remove_deliverydetails_acceptedqty'),
        ('accounting', '0035_salesquotation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('debit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to='accounting.ledger')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='commonApp.deliverydetails')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='commonApp.order')),
            ],
        ),
    ]
