# Generated by Django 4.2.4 on 2024-01-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_ledgerentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
