# Generated by Django 4.2.4 on 2024-01-08 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_alter_ledgerentry_credit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='from_ledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to='accounting.ledger'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymententry',
            name='tax_ledger',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymententry',
            name='to_ledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='accounting.ledger'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PaymentEntryRow',
        ),
    ]
