# Generated by Django 4.2.4 on 2024-01-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0040_remove_paymententry_tax_ledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesquotation',
            name='status',
        ),
        migrations.AlterField(
            model_name='salesquotation',
            name='approval',
            field=models.CharField(choices=[('approved', 'Approved'), ('disapproved', 'Disapproved'), ('pending', 'Pending'), ('inProduction', 'In Production'), ('Produced', 'Produced'), ('deliverPending', 'DeliverPending'), ('completed', 'Completed')], max_length=20),
        ),
    ]
