# Generated by Django 4.2.4 on 2024-01-08 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0029_alter_deliverydetails_payment'),
        ('accounting', '0041_remove_salesquotation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='salesdelivery',
            field=models.ForeignKey(blank=-1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_sales', to='commonApp.deliverydetails'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='delivery',
            field=models.ForeignKey(blank=-1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_purchase', to='commonApp.deliverydetails'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='order',
            field=models.ForeignKey(blank=-1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='commonApp.order'),
        ),
        migrations.AlterField(
            model_name='salesquotation',
            name='approval',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('disapproved', 'disapproved'), ('inProduction', 'in Production'), ('produced', 'produced'), ('deliverPending', 'deliverPending'), ('completed', 'completed')], default='pending', max_length=20),
        ),
    ]
