# Generated by Django 4.2.4 on 2024-01-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0042_ledgerentry_salesdelivery_alter_ledgerentry_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='saleorder',
            field=models.ForeignKey(blank=-1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledgerSalesQuotation_entries', to='accounting.salesquotation'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='salesdelivery',
            field=models.ForeignKey(blank=-1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_sales', to='accounting.salesdeliverydetails'),
        ),
    ]
