# Generated by Django 4.2.4 on 2024-01-08 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0044_salesdeliverydetails_duedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recieptentry',
            name='from_ledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments_from', to='accounting.ledger'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recieptentry',
            name='to_ledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments_to', to='accounting.ledger'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recieptentry',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='RecieptEntryRow',
        ),
    ]
