# Generated by Django 4.2.4 on 2024-01-14 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0045_recieptentry_from_ledger_recieptentry_to_ledger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='ledger',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='current_balance',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='ledger_limit',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='ledger_limitLeft',
        ),
        migrations.AddField(
            model_name='ledger',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
