# Generated by Django 4.2.4 on 2024-01-14 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0046_remove_supplier_ledger_remove_supplier_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='object_id',
        ),
        migrations.AddField(
            model_name='ledger',
            name='ledgerUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
