# Generated by Django 4.2.4 on 2024-01-15 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0047_remove_ledger_content_type_remove_ledger_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='ledgerUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
