# Generated by Django 4.2.4 on 2023-12-12 02:45

import commonApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('unit_of_measurement', models.CharField(choices=[('Piece', 'Piece'), ('Liter', 'Liter'), ('Meter', 'Meter'), ('Centimeter', 'Centimeter')], default='Piece', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Qty', models.PositiveIntegerField()),
                ('costing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonApp.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('productCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productSelling', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image0', models.ImageField(upload_to=commonApp.models.get_image_filename)),
                ('image1', models.ImageField(upload_to=commonApp.models.get_image_filename)),
                ('image2', models.ImageField(upload_to=commonApp.models.get_image_filename)),
                ('image3', models.ImageField(upload_to=commonApp.models.get_image_filename)),
                ('image4', models.ImageField(upload_to=commonApp.models.get_image_filename)),
                ('image5', models.ImageField(upload_to=commonApp.models.get_image_filename)),
                ('image6', models.ImageField(upload_to=commonApp.models.get_image_filename)),
                ('image7', models.ImageField(upload_to=commonApp.models.get_image_filename)),
                ('image8', models.ImageField(upload_to=commonApp.models.get_image_filename)),
                ('image9', models.ImageField(upload_to=commonApp.models.get_image_filename)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonApp.productbrand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonApp.productcategory')),
            ],
        ),
    ]
