# Generated by Django 4.2.4 on 2023-12-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0002_productmaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaterial',
            name='calculation_unit',
        ),
        migrations.RemoveField(
            model_name='productmaterial',
            name='unit_cost',
        ),
        migrations.AddField(
            model_name='material',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='productmaterial',
            name='material',
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='material',
            field=models.ManyToManyField(to='commonApp.material'),
        ),
    ]
