# Generated by Django 4.2.4 on 2023-12-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0004_alter_product_description_alter_product_image0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
