# Generated by Django 4.2.4 on 2023-12-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0005_order_final_price_order_supplier_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
