# Generated by Django 4.2.4 on 2023-12-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0007_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
