# Generated by Django 4.2.4 on 2023-12-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0008_order_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_approved',
            field=models.CharField(choices=[('approved', 'Approved'), ('disapproved', 'Disapproved'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
