# Generated by Django 4.2.4 on 2023-12-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0009_alter_order_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='agent_commission_per_quantal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_per_quantal',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
