# Generated by Django 4.2.4 on 2023-12-16 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commonApp', '0010_alter_order_agent_commission_per_quantal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_type', models.CharField(choices=[('dispatch', 'Dispatch'), ('delivery', 'Delivery')], max_length=20)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('date_of_delivery', models.DateField()),
                ('no_of_bags', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('jute_bags', models.PositiveIntegerField()),
                ('plastic_bags', models.PositiveIntegerField()),
                ('fssi', models.PositiveIntegerField()),
                ('loose', models.PositiveIntegerField()),
                ('final_quantity_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonApp.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
