# Generated by Django 4.2.4 on 2023-12-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0012_deliverydetails_created_at_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
