# Generated by Django 4.2.4 on 2023-12-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0013_alter_deliverydetails_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverydetails',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
