# Generated by Django 4.2.4 on 2023-12-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0014_remove_deliverydetails_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetails',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
