# Generated by Django 4.2.4 on 2023-12-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0015_deliverydetails_created_at_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity_left',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
