# Generated by Django 4.2.4 on 2023-12-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0016_order_quantity_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
