# Generated by Django 4.2.4 on 2023-12-28 09:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0019_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocateMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('quantity_per_piece', models.IntegerField()),
                ('order_quantity', models.IntegerField()),
                ('required', models.IntegerField()),
                ('available', models.IntegerField()),
                ('allocated', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('purchase', 'Purchase'), ('return', 'Return')], default='purchase', max_length=10)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cost_of_single', models.DecimalField(decimal_places=2, max_digits=50)),
                ('cost_of_all', models.DecimalField(decimal_places=2, max_digits=50)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=50)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commonApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('purchase', 'Purchase'), ('sales', 'Sales')], default='purchase', max_length=10)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cost_of_single', models.DecimalField(decimal_places=2, max_digits=40)),
                ('cost_of_all', models.DecimalField(decimal_places=2, max_digits=50)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=50)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commonApp.material')),
            ],
        ),
    ]
