# Generated by Django 4.2.4 on 2023-12-28 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0020_allocatematerial_productstock_materialstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commonApp.deliverydetails'),
        ),
    ]
