# Generated by Django 4.2.4 on 2024-01-04 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0023_deliverydetails_bardana_deliverydetails_brokerage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetails',
            name='dueDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='payment',
            field=models.CharField(choices=[('due', 'Due'), ('paid', 'Paid')], default='Due', max_length=20),
        ),
    ]
