# Generated by Django 4.2.4 on 2024-01-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0024_deliverydetails_duedate_deliverydetails_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetails',
            name='acceptedqty',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
