# Generated by Django 4.2.4 on 2024-01-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0025_deliverydetails_acceptedqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity_left',
            field=models.FloatField(default=0),
        ),
    ]
