# Generated by Django 4.2.4 on 2024-01-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0026_alter_order_quantity_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverydetails',
            name='acceptedqty',
        ),
    ]
