# Generated by Django 4.2.4 on 2024-01-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0028_alter_deliverydetails_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='payment',
            field=models.CharField(choices=[('pending', 'Pending'), ('due', 'Due'), ('paid', 'Paid')], default='due', max_length=20),
        ),
    ]
