# Generated by Django 4.2.4 on 2024-01-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0029_alter_deliverydetails_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packaging_products',
            field=models.ManyToManyField(blank=True, related_name='sales_products', to='commonApp.product'),
        ),
    ]
