# Generated by Django 4.2.4 on 2024-01-15 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_remove_billing_company_industry_and_more'),
        ('commonApp', '0030_product_packaging_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetails',
            name='billing_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.billing_company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='partyAddress',
            field=models.CharField(choices=[('dispatch', 'Dispatch'), ('delivery', 'Delivery')], default='address', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='partyName',
            field=models.CharField(choices=[('dispatch', 'Dispatch'), ('delivery', 'Delivery')], default='Company', max_length=20),
            preserve_default=False,
        ),
    ]
