# Generated by Django 4.2.4 on 2024-01-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0031_deliverydetails_billing_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetails',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliverydetails',
            name='row_type',
            field=models.CharField(choices=[('dispatch', 'Dispatch'), ('delivery', 'Delivery')], max_length=50),
        ),
    ]
