# Generated by Django 4.2.4 on 2024-01-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0032_deliverydetails_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
