# Generated by Django 4.2.4 on 2024-01-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0033_alter_deliverydetails_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stat',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
