# Generated by Django 4.2.4 on 2024-01-15 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0034_order_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stat',
        ),
    ]
