# Generated by Django 4.2.4 on 2024-01-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0035_remove_order_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='partyAddress',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='deliverydetails',
            name='partyName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_approved',
            field=models.CharField(choices=[('approved', 'Approved'), ('disapproved', 'Disapproved'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
