# Generated by Django 4.2.4 on 2024-01-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0036_alter_deliverydetails_partyaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetails',
            name='pendingAmt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
