# Generated by Django 4.2.4 on 2024-01-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0037_deliverydetails_pendingamt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agent_commission_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
